# add_executable(producer
#     src/main.cpp
#     src/CliOptions.cpp
#     src/RandomPayloadGenerator.cpp
#     src/SharedRingBuffer.cpp
#     src/ProducerApplication.cpp
# )
#
# target_include_directories(producer PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
# target_link_libraries(producer PRIVATE common)
